name: Bug Report
description: Use this user-friendly form to report bugs to us
title: "[Bug] "
labels: [Bug]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out this report form to help us help you easier. Thanks!
  # First let's ask the user about the bug
  - type: textarea
    id: description
    attributes:
      label: Description
      description: "Please be holistic in your description: Even seemingly trivial stuff might contain the important clue to fix the bug!"
      placeholder: Describe your bug here
    validations:
      required: true
  # Also ask them to describe reproducing the bug
  - type: textarea
    id: reproducing
    attributes:
      label: Reproducing
      description: "Please tell us an easy way how we can reproduce the bug so we know where to look. The more contextual information you include, the better!"
      placeholder: Describe the steps necessary to reproduce this bug
    validations:
      required: true
  # Now the version
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: "What version of Zettlr are you running? Choose **Stable** if you are simply using the regular install."
      options:
        - Stable (most recent version)
        - Stable (but an older version)
        - Beta (if applicable)
        - Nightly
        - Right off the develop branch
    validations:
      required: true
  # Including the specific one if they provide it
  - type: input
    id: specific-version
    attributes:
      label: Specify version
      description: Optional, but it is encouraged to add this information (especially if we release many versions in a short span of time)
      placeholder: e.g. 1.8.9 or 1.8.9+nightly-20210628
    validations:
      required: false
  # Also, we need to know the operating system(s) where this happens
  - type: checkboxes
    id: scope
    attributes:
      label: Your Operating System
      description: Please tell us what operating system you are using. If you were able to check other operating systems and they have the same bug, please check all operating systems that apply!
      options:
        - label: Windows
        - label: macOS
        - label: Linux
    validations:
      required: true
  # The architecture might come in handy
  - type: checkboxes
    id: arch
    attributes:
      label: Architecture
      description: On which architecture(s) does this bug appear?
      options:
        - label: Intel 64bit
        - label: ARM 64bit
    validations:
      required: true
  - type: input
    id: os-version
    attributes:
      label: Operating System
      description: Which operating system(s) are you running?
      placeholder: e.g. Big Sur 11.4, Linux Mate, pop!_OS, Windows 10
    validations:
      required: true
  - type: textarea
    id: more-info
    attributes:
      label: Additional Information
      description: If applicable, feel free to include more info, such as log outputs or error messages you are seeing.
  - type: markdown
    id: outro
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report.
        We'll get back to you as soon as possible.
        Note that we might have additional questions so
        please make sure to check your notifications in case need some more info!
