# I can see that for some issues we'll need that
blank_issues_enabled: true
contact_links:
  - name: Discuss Your Feature Ideas (on Reddit)
    url: https://www.reddit.com/r/Zettlr
    about: Before actually requesting a new feature, make sure to discuss it with fellow users first.
  - name: Discuss Your Feature Ideas (on the Forum)
    url: https://forum.zettlr.com/
    about: Before actually requesting a new feature, make sure to discuss it with fellow users first.
