name: Run the application's tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup NodeJS 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install packages in main and source directories
      run: npm install && cd ./source && npm install && cd ..
    - name: Test with mocha
      run: npm test
